######################################################################
# Automatically generated by qmake (3.0) ?? ?? 27 21:07:09 2016
######################################################################

TEMPLATE = app
TARGET = SliderDialog

# Input
HEADERS += include/CustomSlider.h \
           include/MainDia
FORMS += res/ui/MainDialog.ui rDisplay.ui
SOURCES += src/CustomSlider.cpp \
           src/main.cpp \
           src/MainDialog.cpp \
           src/UiSliderDisplay.cpp
